/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlhv;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class QL_HV extends javax.swing.JFrame {

    /**
     * Creates new form QL_HV
     */
    public QL_HV() {
        initComponents();
        Show_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbMa = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbQue = new javax.swing.JLabel();
        lbDiem = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtQue = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        lbTK = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        btnHienthi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHocvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ HỌC VIÊN");

        lbMa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMa.setText("Mã Học Viên");

        lbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTen.setText("Tên Học Viên");

        lbQue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbQue.setText("Quê Quán");

        lbDiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDiem.setText("Điểm thi");

        txtMa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtQue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTK.setText("Tìm kiếm theo tên");

        txtTimkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnHienthi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHienthi.setText("Hiển thị");
        btnHienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienthiActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnTimkiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimkiemMouseClicked(evt);
            }
        });

        tbHocvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Học Viên", "Họ tên", "Quê quán", "Điểm thi"
            }
        ));
        tbHocvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHocvienMouseClicked(evt);
            }
        });
        tbHocvien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbHocvienKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbHocvien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMa)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSua)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbTK)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTimkiem)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbQue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtQue, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnXoa)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnThoat))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lbTen))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnHienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMa)
                    .addComponent(lbQue)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTen)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDiem)
                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHienthi)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTK)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int Dem(){
        int dem =0;
        try {
            Connect cn = new Connect();
            ResultSet rs = cn.GetData("hocvien");
            while (rs.next()){
                dem++;
            }
           cn.Close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void Show_Table(){
        DefaultTableModel model = (DefaultTableModel) tbHocvien.getModel();
        model.setRowCount(Dem());
       
        try{
            Connect cn = new Connect();
            ResultSet rs = cn.GetData("hocvien");
             int i =0;
            while(rs.next()){
                tbHocvien.setValueAt(rs.getString("maHv"),i,0);
                tbHocvien.setValueAt(rs.getString("tenHv"), i, 1);
                tbHocvien.setValueAt(rs.getString("queQuan"), i, 2);
                tbHocvien.setValueAt(rs.getString("diemThi"), i, 3);
                i++;
            }
            cn.Close();
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void Delete(String Ma){
        Connect con;
        try{
            con = new Connect();
            con.Delete(Ma);
            con.Close();
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       String ma = txtMa.getText();
       if(check(ma) == true){
           int result = JOptionPane.showConfirmDialog(null,
    "Bạn có muốn xóa học viên này không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
           if(result == JOptionPane.YES_OPTION){
               Delete(ma);
               Show_Table();
           }else{
               
           }
       }else{
           JOptionPane.showMessageDialog(null,"Mã học viên không trùng với dữ liệu!!!");
       }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienthiActionPerformed
        Show_Table();// TODO add your handling code here:
    }//GEN-LAST:event_btnHienthiActionPerformed
 public void Clear_Table(){
        DefaultTableModel mod = (DefaultTableModel) tbHocvien.getModel();
        mod.setRowCount(0);
        mod.setRowCount(Dem());
    }
    public void Timkiem(String Hoten){
        Clear_Table();
        try{
            Connect con = new Connect();
            ResultSet rs = con.GetTimkiem(Hoten);
            int i =0;
            while(rs.next()){
                tbHocvien.setValueAt(rs.getString("maHv"), i, 0);
                tbHocvien.setValueAt(rs.getString("tenHv"), i, 1);
                tbHocvien.setValueAt(rs.getString("queQuan"), i, 2);
                tbHocvien.setValueAt(rs.getString("diemThi"), i, 3);
                i++;
            }
            con.Close();
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimkiemMouseClicked
        String Hoten = txtTimkiem.getText();
        Timkiem(Hoten);       // TODO add your handling code here:
    }//GEN-LAST:event_btnTimkiemMouseClicked
    private boolean check(String Ma){
        boolean check = false;
        try{
            Connect con = new Connect();
            ResultSet rs = con.GetData("hocvien");
            while(rs.next()){
                if(rs.getString(1).equals(Ma)==true){
                    check = true;
                }
            }
            con.Close();
            
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }
        return check;
    }
    public void Insert(){
        String Ma = txtMa.getText();
        String Hoten = txtTen.getText();
        String Quequan = txtQue.getText();
        float Diem = Float.parseFloat(txtDiem.getText());
        Connect con;
        try{ con = new Connect();
         con.Insert(Ma, Hoten, Quequan, Diem);
        con.Close();
      
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        txtMa.setEnabled(true);
        String Ma = txtMa.getText();
        String Hoten = txtTen.getText();
        String Quequan = txtQue.getText();
        String Diem = txtDiem.getText();
        Ma = Ma.replaceAll("", "");
        Hoten = Hoten.replaceAll("", "");
        Quequan = Quequan.replaceAll("","");
        Diem = Diem.replaceAll("", "");
        if(txtMa.getText().equals("")==true||txtTen.equals("")==true||
                txtQue.equals("")==true||txtDiem.equals("")==true){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập dữ liệu");
        }else{
            if(check(Ma)==true){
                JOptionPane.showMessageDialog(null,"Mã học viên bị trùng. Xin vui lòng nhập lại!!!");
            }else{
                Insert();
            Show_Table();
            JOptionPane.showMessageDialog(null,"Đã thêm thành công!!!");
            }
            
        }
    }//GEN-LAST:event_btnThemMouseClicked
    public void Update(){
        Connect con;
        try{
            con = new Connect();
            con.Update(txtMa.getText(),txtTen.getText(),txtQue.getText(),Float.parseFloat(txtDiem.getText()));
            con.Close();
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Connect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        if(check(txtMa.getText()) == true){
            Update();
            Show_Table();
            JOptionPane.showMessageDialog(null,"Bạn đã sửa thành công!!!");
        }else{
            JOptionPane.showMessageDialog(null,"Mã học viên không trùng với dữ liệu cần sửa!");
        }
    }//GEN-LAST:event_btnSuaMouseClicked
    
    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       int result = JOptionPane.showConfirmDialog(null,
               "Bạn có muốn thoát không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(result == JOptionPane.YES_OPTION){
           this.setVisible(false);
           
       }else{
           
       }      
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tbHocvienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbHocvienKeyReleased
         if(evt.getKeyCode()== KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
             txtMa.setEditable(false);
             txtTen.setText((String) tbHocvien.getValueAt(tbHocvien.getSelectedRow(),0));
             txtQue.setText((String) tbHocvien.getValueAt(tbHocvien.getSelectedRow(),1));
             txtDiem.setText((String) tbHocvien.getValueAt(tbHocvien.getSelectedRow(),2));
    }//GEN-LAST:event_tbHocvienKeyReleased
    }
public void Show_Detail() {
        try {
            Connect pt = new Connect();
            ResultSet rs = pt.GetData("hocvien");
            int i = tbHocvien.getSelectedRow();

            txtMa.setText((String) tbHocvien.getValueAt(i, 0));
            txtTen.setText((String) tbHocvien.getValueAt(i, 1));
            txtQue.setText((String) tbHocvien.getValueAt(i, 2));
            txtDiem.setText((String) tbHocvien.getValueAt(i, 3));
            pt.Close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QL_HV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void tbHocvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHocvienMouseClicked
       Show_Detail();
    }//GEN-LAST:event_tbHocvienMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_HV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_HV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_HV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_HV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_HV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienthi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDiem;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbQue;
    private javax.swing.JLabel lbTK;
    private javax.swing.JLabel lbTen;
    private javax.swing.JTable tbHocvien;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtQue;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables

    
}
