/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlcb;

import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pc
 */
public class QLCB extends javax.swing.JFrame {

    /**
     * Creates new form QLCB
     */
    public QLCB() {
        initComponents();
        Show_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        txtMaCB = new javax.swing.JTextField();
        txtChucvu = new javax.swing.JTextField();
        txtHsluong = new javax.swing.JTextField();
        txtPhucap = new javax.swing.JTextField();
        txtTim = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCanBo = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ CÁN BỘ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã CB");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Chức vụ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Hệ số lương");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Phụ cấp");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tìm kiếm theo tên");

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotenActionPerformed(evt);
            }
        });

        txtMaCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCBActionPerformed(evt);
            }
        });

        txtChucvu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChucvuActionPerformed(evt);
            }
        });

        txtHsluong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHsluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHsluongActionPerformed(evt);
            }
        });

        txtPhucap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhucap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhucapActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTim.setText("Tìm kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Hiển thị");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Thoát");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tbCanBo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Cán Bộ", "Họ tên", "Chức vụ", "Hệ số lương", "Phụ cấp"
            }
        ));
        tbCanBo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCanBoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCanBo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtPhucap, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHsluong))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHsluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhucap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnTim)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotenActionPerformed

    private void txtMaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCBActionPerformed

    private void txtChucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChucvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChucvuActionPerformed

    private void txtHsluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHsluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHsluongActionPerformed

    private void txtPhucapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhucapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhucapActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    public int Dem(){
        int dem =0;
        try {
            Connect cn = new Connect();
            ResultSet rs = cn.GetData("canbo");
            while(rs.next()){
                dem++;
            }
            cn.Close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dem;
    }
    public void Show_Table(){
        DefaultTableModel mod = (DefaultTableModel) tbCanBo.getModel();
        mod.setRowCount(Dem());
        try {
            Connect cn = new Connect();
            ResultSet rs = cn.GetData("canbo");
            int i =0;
            while(rs.next()){
                tbCanBo.setValueAt(rs.getString("MaCB"), i, 0);
                tbCanBo.setValueAt(rs.getString("Hoten"), i, 1);
                tbCanBo.setValueAt(rs.getString("Chucvu"), i, 2);
                tbCanBo.setValueAt(rs.getString("Hsluong"), i, 3);
                tbCanBo.setValueAt(rs.getString("Phucap"), i, 4);
                i++;
            }
            cn.Close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Show_Table();
    }//GEN-LAST:event_jButton5ActionPerformed
    private boolean check(String Ma){
        boolean check = false;
        try {
            Connect cn = new Connect();
            ResultSet rs = cn.GetData("canbo");
            while(rs.next()){
                if(rs.getString(1).equals(Ma)==true){
                    check = true;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
        return check;
    }
    public void Insert(){
        String MaCB = txtMaCB.getText();
        String Hoten = txtHoten.getText();
        String Chucvu = txtChucvu.getText();
        float Hsluong = Float.parseFloat(txtHsluong.getText());
        float Phucap = Float.parseFloat(txtPhucap.getText());
        try {
            Connect cn = new Connect();
            cn.Insert(MaCB, Hoten, Chucvu, Hsluong, Phucap);
            cn.Close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String MaCB = txtMaCB.getText();
        String Hoten = txtHoten.getText();
        String Chucvu = txtChucvu.getText();
        String Hsluong = txtHsluong.getText();
        String Phucap = txtPhucap.getText();
        MaCB = MaCB.replaceAll("", "");
        Hoten = Hoten.replaceAll("", "");
        Chucvu = Chucvu.replaceAll("", "");
        Hsluong = Hsluong.replaceAll("", "");
        Phucap = Phucap.replaceAll("", "");
        if(txtMaCB.getText().equals("")==true||txtHoten.getText().equals("")==true||
                txtChucvu.getText().equals("")==true||txtHsluong.getText().equals("")==true||
                txtPhucap.getText().equals("")==true){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập đủ dữ liệu!!!");
        }else{
            if(check(MaCB)== true){
                JOptionPane.showMessageDialog(null,"Mã cán bộ bị trùng xin vui lòng nhập lại");
            }else{
                Insert();
                Show_Table();
                JOptionPane.showMessageDialog(null,"Bạn đã thêm thành công.");
                
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed
    public void Update(){
        try {
            Connect cn = new Connect();
            cn.Update(txtMaCB.getText(),txtHoten.getText(),txtChucvu.getText(),
                    Float.parseFloat(txtHsluong.getText()),Float.parseFloat(txtPhucap.getText()));
            cn.Close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if(check(txtMaCB.getText())==true){
            Update();
            Show_Table();
            JOptionPane.showMessageDialog(null,"Bạn đã sửa thành công!!!");
        }else{
            JOptionPane.showMessageDialog(null,"Mã cán bộ không trùng với dữ liệu!!!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed
    public void Delete(String MaCB){
        try {
            Connect cn = new Connect();
            cn.Delete(MaCB);
            cn.Close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String MaCB = txtMaCB.getText();
       if(check(MaCB)==true){
           int result = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa cán bộ này không?","Thông báo",
                   JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
           if(result == JOptionPane.YES_OPTION){
               Delete(MaCB);
               Show_Table();
               JOptionPane.showMessageDialog(null,"Đã xóa thành công!!!");
           }else{
               
           }
       }else{
           JOptionPane.showMessageDialog(null,"Mã cán bộ không trùng với dữ liệu!!!");
       }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       int rs = JOptionPane.showConfirmDialog(null,"Bạn muốn thoát khỏi chương trình?","Thông báo",
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       if(rs==JOptionPane.YES_OPTION){
           this.setVisible(false);
       }else{
           
       }
    }//GEN-LAST:event_jButton6ActionPerformed
 public void Clear_Table(){
     DefaultTableModel mod = (DefaultTableModel) tbCanBo.getModel();
     mod.setRowCount(0);
     mod.setRowCount(Dem());
 }
 public void Search(String Name){
     Clear_Table();
        try {
            Connect cn = new Connect();
            ResultSet rs = cn.Search(Name);
            int i =0;
            while(rs.next()){
                tbCanBo.setValueAt(rs.getString("MaCB"), i, 0);
                tbCanBo.setValueAt(rs.getString("Hoten"), i, 1);
                tbCanBo.setValueAt(rs.getString("Chucvu"), i, 2);
                tbCanBo.setValueAt(rs.getString("Hsluong"), i, 3);
                tbCanBo.setValueAt(rs.getString("Phucap"), i, 4);
                i++;
            }
            cn.Close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
 }
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        String Name = txtTim.getText();
        Search(Name);
    }//GEN-LAST:event_btnTimActionPerformed

    public void Show_Detail(){
        try {
            Connect cn = new Connect();
            ResultSet rs = cn.GetData("canbo");
            int i = tbCanBo.getSelectedRow();
            
            txtMaCB.setText((String) tbCanBo.getValueAt(i, 0));
            txtHoten.setText((String) tbCanBo.getValueAt(i, 1));
            txtChucvu.setText((String) tbCanBo.getValueAt(i, 2));
            txtHsluong.setText((String) tbCanBo.getValueAt(i, 3));
            txtPhucap.setText((String) tbCanBo.getValueAt(i, 4));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QLCB.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void tbCanBoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCanBoMouseClicked
        Show_Detail();
    }//GEN-LAST:event_tbCanBoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLCB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLCB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbCanBo;
    private javax.swing.JTextField txtChucvu;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtHsluong;
    private javax.swing.JTextField txtMaCB;
    private javax.swing.JTextField txtPhucap;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
